export enum TodoTypesEnum {
  ADD_TODO = 'ADD_TODO',
  REMOVE_TODO = 'REMOVE_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  DEFAULT = 'DEFAULT',
  SHOW_LOADER = 'SHOW_LOADER',
  HIDE_LOADER = 'HIDE_LOADER',
  SHOW_ERROR = 'SHOW_ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',
  FETCH_TODOS = 'FETCH_TODOS'
}
